version: '3.8'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
    working_dir: /app
    restart: unless-stopped

  frontend:
    build:
      context: ./client/client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    working_dir: /app
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
